### ISSUE TITLE
Menu button (desktop and mobile view)

### ISSUE THREAD

**Issue by card0127** [card0127/zerofive#16]
Menu button on desktop view should be bigger. 

@cole0228 
@situ0020 
@baci0008 
@lauranatalia
@heartedmachine

**Comment by heartedmachine** [comment]
Keep in mind.. The bigger the button, the more we need to give space on each sides.

**Comment by card0127** [comment]
I understand Melissa. Here you have a print screen of what I see on my computer. 
Thanks, 
![art start](https://cloud.githubusercontent.com/assets/6353004/6110107/90c6a650-b04d-11e4-85fa-e5cfc5e3f1f8.png)
