### ISSUE TITLE
Validator HTML

### ISSUE THREAD

**Issue by card0127** [card0127/zerofive#18]
Html validator shows a few missing closing tags. 
Print screen attached. 
CSS validator is just fine. 

@cole0228 
@heartedmachine 
@situ0020 
@baci0008 
@lauranatalia 

![invalid markup validation of http pedrosantos info zerofive w3c markup validator](https://cloud.githubusercontent.com/assets/6353004/6109613/0d8cfe04-b04a-11e4-9215-f763afb90b3e.png)

**Comment by heartedmachine** [comment]
This should be done later on when we have a bit more content.. We are currently figuring out all of our stuff. Once the main pages are done and such, then we can validate everything. Right now this is not priority unfortunately.

**Comment by heartedmachine** [comment]
HTML Validation will always have errors because of Jekyll. Ive been checking on a weekly basis and nothing changes.
