### ISSUE TITLE
fix(css): adjust homepage slideshow

### ISSUE THREAD

**Issue by card0127** [card0127/zerofive#21]
I would suggest returning width of slideshow as before just so it doesn't compete with next section background image. 
@heartedmachine 
@baci0008

**Comment by heartedmachine** [comment]
Me and katie thought of a solution, trying to see if it'll make it better.

**Comment by card0127** [comment]
Great thinking. You're always ahead of the game. Thanks

**Comment by heartedmachine** [comment]
Unfortunately can't do what we wanted :( it would require us to remove the 'About Us' Background and I think it's just a great section. We'll stick with the carousel. Made it smaller on bigger screen and big on small screen.
